//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace сампледатабасевалксраугх.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\SampleDataBas" +
            "e.mdf;Integrated Security=True")]
        public string SampleDataBaseConnectionString {
            get {
                return ((string)(this["SampleDataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\TRIVI\\SOURCE\\REPOS\\СА" +
            "МПЛЕДАТАБАСЕВАЛКСРАУГХ\\САМПЛЕДАТАБАСЕВАЛКСРАУГХ\\BIN\\DEBUG\\SAMPLEDATABASE.MDF;Int" +
            "egrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=Fa" +
            "lse")]
        public string C__USERS_TRIVI_SOURCE_REPOS_САМПЛЕДАТАБАСЕВАЛКСРАУГХ_САМПЛЕДАТАБАСЕВАЛКСРАУГХ_BIN_DEBUG_SAMPLEDATABASE_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_TRIVI_SOURCE_REPOS_САМПЛЕДАТАБАСЕВАЛКСРАУГХ_САМПЛЕДАТАБАСЕВАЛКСРАУГХ_BIN" +
                    "_DEBUG_SAMPLEDATABASE_MDFConnectionString"]));
            }
        }
    }
}
